- name: Clone or update application repository
  git:
    repo: "https://github.com/sunilemj/devops-production-project.git"
    dest: /home/ubuntu/devops-production-project
    version: main
    force: yes
